application: zero-thirty-sixty
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: PIL
  version: "1.1.7"
- name: jinja2
  version: "2.6"

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: .*
  script: index.routing
